// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsJoUYAYnkMnP0867gBF9_YQCyFJaQXkw',
    appId: '1:55014903883:web:11c2c9a4696fb88d5a3dce',
    messagingSenderId: '55014903883',
    projectId: 'triptourbookingsystem-5f7d7',
    authDomain: 'triptourbookingsystem-5f7d7.firebaseapp.com',
    databaseURL:
        'https://triptourbookingsystem-5f7d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'triptourbookingsystem-5f7d7.firebasestorage.app',
    measurementId: 'G-HWD8ZZJGVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJdFWLkMz6sAdfAEud9V709rgm-bFhezY',
    appId: '1:55014903883:android:87c8b187c8bf2d1b5a3dce',
    messagingSenderId: '55014903883',
    projectId: 'triptourbookingsystem-5f7d7',
    databaseURL:
        'https://triptourbookingsystem-5f7d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'triptourbookingsystem-5f7d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANRSqq3WKHrSER8mUSTYbXgqBfhZBfPHs',
    appId: '1:55014903883:ios:75a2ede479af9c325a3dce',
    messagingSenderId: '55014903883',
    projectId: 'triptourbookingsystem-5f7d7',
    databaseURL:
        'https://triptourbookingsystem-5f7d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'triptourbookingsystem-5f7d7.firebasestorage.app',
    androidClientId:
        '55014903883-bggdskhqgo678tki0vjhpq5fk7kqrs7m.apps.googleusercontent.com',
    iosClientId:
        '55014903883-9d748rtdbhe2plqlad7vpiq64ruch4i2.apps.googleusercontent.com',
    iosBundleId: 'com.example.triptourApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANRSqq3WKHrSER8mUSTYbXgqBfhZBfPHs',
    appId: '1:55014903883:ios:75a2ede479af9c325a3dce',
    messagingSenderId: '55014903883',
    projectId: 'triptourbookingsystem-5f7d7',
    databaseURL:
        'https://triptourbookingsystem-5f7d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'triptourbookingsystem-5f7d7.firebasestorage.app',
    androidClientId:
        '55014903883-bggdskhqgo678tki0vjhpq5fk7kqrs7m.apps.googleusercontent.com',
    iosClientId:
        '55014903883-9d748rtdbhe2plqlad7vpiq64ruch4i2.apps.googleusercontent.com',
    iosBundleId: 'com.example.triptourApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsJoUYAYnkMnP0867gBF9_YQCyFJaQXkw',
    appId: '1:55014903883:web:bf6647cd5a1599325a3dce',
    messagingSenderId: '55014903883',
    projectId: 'triptourbookingsystem-5f7d7',
    authDomain: 'triptourbookingsystem-5f7d7.firebaseapp.com',
    databaseURL:
        'https://triptourbookingsystem-5f7d7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'triptourbookingsystem-5f7d7.firebasestorage.app',
    measurementId: 'G-GMF4EQN2SJ',
  );
}
